/**:                                                              # 全局参数
  ros__parameters:
    # 世界大小 [长, 宽]，单位：米
    world_size: [12.00,7.00]
    # 消息发布频率，单位：秒
    frequency: 0.2
    # 初始机器人 坐标
    START_POINT: [0.30,0.30]

visual_location_node:
  ros__parameters:
    # 相机高度，单位：毫米
    camera_height: 960.0
    # 篮筐高度，单位：毫米
    hoop_height: 3050.0
    # 相机内参
    fx: 978.884521484375
    fy: 978.8125  
    cx: 1019.759765625
    cy: 783.3111572265625
    # 相机俯仰角
    pitch: 0.0
    # 相机频率
    camera_frequency: 0.1

car_controller:                                                   ##避障的参数
  ros__parameters:
    # 最大速度限制，单位：米/秒
    max_speed: 4.0
    # 最大加速度限制，单位：米/秒²
    max_accel: 0.3
    # 目标点跟踪权重，值越大越倾向于跟踪目标点
    weight_goal: 0.0
    # 速度平滑权重，值越大速度变化越平滑
    weight_velocity: 5.0
    # 加速度平滑权重，值越大加速度变化越平滑
    weight_accel: 1.0
    # 障碍物避障权重，值越大越倾向于远离障碍物
    weight_obstacle: 1.0
    # 边界避障权重，值越大越倾向于远离边界
    weight_boundary: 1.0
    # 车辆半径，用于碰撞检测，单位：米
    car_radius: 0.5
    obstacle_visual_radius: 0.3
    # 边界安全距离，单位：米
    boundary_safe_distance: 1.0
    # 避障安全裕度，单位：米
    avoidance_margin: 1.0
    # 警告区域距离，单位：米
    warning_zone_distance: 2.0
    # 混合安全距离，单位：米
    blend_safe_dist: 0.5
    # 手动控制切换距离，单位：米
    manual_override_dist: 10.0
    # 最大预期障碍物速度，单位：米/秒
    max_expected_obstacle_speed: 1.0
    # DBSCAN聚类算法的邻域半径
    dbscan_eps: 0.5
    # DBSCAN聚类算法的最小样本数
    dbscan_min_samples: 3
    # 历史轨迹最大长度
    max_history_length: 10.0
    # 预测时域长度，用于轨迹规划
    prediction_horizon: 5
    # 2D激光到中心的 距离
    Two_D_position: [19.92,-25.04] 

laser_position_node:                                              # 定位的参数
    ros__parameters:
    # 激光传感器判断是否被遮挡的误差 阈值
      LASER_ALLOWED_NOISE: 1.0 
    # 3D Laser 传感器测量 标准差 x y angle
      three_D_noise_std: [0.035,0.07,0.05] 
    # 激光传感器测量 标准差 x y angle
      measurement_noise_std: [0.01,0.5,0.1] 
    # 激光到中心的 距离
      DELTA_DISTANCE: 0.1247 
    # 激光角度偏移 角度
      angle_bios : 180.0
    # 3D laser到中心的 坐标 m
      three_D_position: [0.0,0.0] 
    # 3D 雷达的坐标系的x轴转角 度
      three_d_angle : -90.0
    # 单点激光的角度分布 角度
      laser_angle_distribution : [0.0,72.0,144.0,216.0,288.0]